git remote set-url origin https://TOKEN@github.com/tree-fit/treefit-frontend.git



.github/workflows/ci_cd.yml


name: Treefit Backend CI/CD

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/ubuntu/treefit-backend

    steps:
      - name: Take pull of staging
        run: |
          git pull origin staging

      - name: Build and reload pm2
        run: |
          pm2 reload 0


          mkdir actions-runner-frontend && cd actions-runner-frontend


          pm2 start ./run.sh --name github_runner_frontend --interpreter bash
